#!/bin/bash
set -u -e -C
shopt -s failglob

while IFS= read line; do
    echo "> ${line}"
    units <<<"${line}" || true
    echo
done <<.
1
100 [s]
20 [m] / 2
20 [m] / 2 [m]
1 [m] + 2 [m]
2 [m] * 3 [m]
4 [kg] / 2 [kg]
2 [m/s] * 4 [s]
50 [/s]
100 [m/s] / 4[s]
12  [kg m2 / s3 A]
4 [N m/s2]
(10 [m/s] ^ 2 + 3[m2/s2]) / 5[m]
.
