# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-18.25

# User packages to be built.
packages:
- .
- dep/shuntingYard
- dep/robust-int
