# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/


resolver: lts-22.0


packages:

  - .


extra-deps:

  - git: https://github.com/s5k6/robust-int
    commit: 3e3216ded51bd973cb5d6ba25dccf50445d53011

  - git: https://github.com/s5k6/shuntingYard
    commit: 325753ddc3ce92ae497d1d8574e5147ec573eab8
